import { useEffect, useMemo, useState } from 'react'
import { STORY_THEMES, buildStory, type StoryTheme } from '../../data/storyGenerator'
import { toIAST } from '../../services/sanskrit'
import { speakWithFallback } from '../../services/speech'
import { api } from '../../services/api'
import { loadStoryThemes } from '../../services/contentDb'
import { saveStoryToDb, syncStoriesFromDb, deleteStoryFromDb, type SavedStory } from '../../services/userDb'
import { useLanguage } from '../../context/LanguageContext'

export default function StoryGeneratorPage() {
  const { t, lang } = useLanguage()
  const [themes, setThemes] = useState<StoryTheme[]>(STORY_THEMES)
  const [saved, setSaved] = useState<SavedStory[]>([])
  const [themeId, setThemeId] = useState(STORY_THEMES[0].id)
  const [w1, setW1] = useState(STORY_THEMES[0].words[0].sa)
  const [w2, setW2] = useState(STORY_THEMES[0].words[1].sa)
  const [story, setStory] = useState<{ sa: string; en: string; hi: string }[] | null>(null)
  const [aiNote, setAiNote] = useState('')
  const [busy, setBusy] = useState(false)
  const [speaking, setSpeaking] = useState(false)

  useEffect(() => {
    let live = true
    loadStoryThemes().then((th) => {
      if (!live) return
      setThemes(th)
      if (!th.some((x) => x.id === themeId)) {
        setThemeId(th[0].id)
        setW1(th[0].words[0].sa)
        setW2(th[0].words[1].sa)
      }
    })
    syncStoriesFromDb().then((rows) => {
      if (live && rows) setSaved(rows)
    })
    return () => {
      live = false
    }
  }, [])

  const theme = useMemo(() => themes.find((th) => th.id === themeId) ?? themes[0], [themes, themeId])

  const pickWord = (slot: 1 | 2) => {
    const others = theme.words.filter((w) => w.sa !== (slot === 1 ? w2 : w1))
    const w = others[Math.floor(Math.random() * others.length)]
    if (slot === 1) setW1(w.sa)
    else setW2(w.sa)
  }

  const generate = async () => {
    setBusy(true)
    setStory(null)
    setAiNote('')
    const wordA = theme.words.find((w) => w.sa === w1) || theme.words[0]
    const wordB = theme.words.find((w) => w.sa === w2) || theme.words[1]
    try {
      const res = await api.tutor.chat(
        [{ role: 'system', content: 'Write a 5 sentence Sanskrit story for children using the words {w1} and {w2}. Give each Sanskrit sentence followed by its English translation, numbered.' }, { role: 'user', content: `theme: ${theme.title}, words: ${wordA.sa} (${wordA.en}), ${wordB.sa} (${wordB.en})` }],
        { mode: 'story' },
      )
      const lines = res.reply
        .split(/\n+/)
        .filter((l) => l.trim() && !/^\d+[.)]/.test(l.trim()) === false || l.trim().length > 2)
        .map((l) => l.replace(/^\d+[.)]\s*/, '').trim())
        .filter(Boolean)
      const pairs: { sa: string; en: string }[] = []
      let pending: string | null = null
      for (const l of lines) {
        if (/[\u0900-\u097F]/.test(l) && l.length < 200) {
          if (pending) pairs.push({ sa: pending, en: '' })
          pending = l
        } else if (pending) {
          pairs.push({ sa: pending, en: l })
          pending = null
        }
      }
      if (pending) pairs.push({ sa: pending, en: '' })
      if (pairs.length >= 3) {
        setStory(pairs)
        setAiNote(t('✨ Generated by the AI tutor'))
        saveStoryToDb(theme.id, theme.title, wordA.sa, wordB.sa, 'ai', pairs).then(() =>
          syncStoriesFromDb().then((rows) => {
            if (rows) setSaved(rows)
          }),
        )
        return
      }
    } catch {
      /* offline below */
    }
    const built = buildStory(theme, wordA.sa, wordB.sa)
    setStory(built)
    setAiNote(t('Story built from templates — connect the AI tutor for fresh stories.'))
    saveStoryToDb(theme.id, theme.title, wordA.sa, wordB.sa, 'template', built).then(() =>
      syncStoriesFromDb().then((rows) => {
        if (rows) setSaved(rows)
      }),
    )
  }

  const deleteSaved = (id: string) => {
    deleteStoryFromDb(id)
    setSaved((s) => s.filter((x) => x.id !== id))
  }

  const speakStory = () => {
    if (!story) return
    const full = story.map((s) => s.sa).join(' ')
    speakWithFallback(full, (isSpeaking) => setSpeaking(isSpeaking))
  }

  const wordMeaning = (sa: string) => theme.words.find((w) => w.sa === sa)

  return (
    <div>
      <div className="page-header">
        <h2>{t('📖 Story Generator')}</h2>
        <p>{t('Pick a theme and two words — instantly get a short Sanskrit story with translation, ready to hear aloud.')}</p>
      </div>

      <div className="card" style={{ maxWidth: 760, margin: '0 auto', padding: 24 }}>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 16 }}>
          {themes.map((th) => (
            <button
              key={th.id}
              className={`btn btn-sm ${themeId === th.id ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => { setThemeId(th.id); setW1(th.words[0].sa); setW2(th.words[1].sa); setStory(null) }}
            >
              {th.emoji} {t(th.title)}
            </button>
          ))}
        </div>

        <div className="card" style={{ padding: 16, marginBottom: 16, background: 'rgba(255,152,0,0.06)' }}>
          <p style={{ margin: '0 0 10px', fontWeight: 600 }}>{t('Choose two words for your story')}</p>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>
            <select className="btn btn-sm btn-secondary" style={{ height: 36 }} value={w1} onChange={(e) => setW1(e.target.value)}>
              {theme.words.map((w) => <option key={w.sa} value={w.sa}>{w.sa} — {lang === 'hi' ? w.hi : w.en}</option>)}
            </select>
            <select className="btn btn-sm btn-secondary" style={{ height: 36 }} value={w2} onChange={(e) => setW2(e.target.value)}>
              {theme.words.map((w) => <option key={w.sa} value={w.sa}>{w.sa} — {lang === 'hi' ? w.hi : w.en}</option>)}
            </select>
            <button className="btn btn-sm btn-secondary" onClick={() => { pickWord(1); pickWord(2) }}>🎲 {t('Random')}</button>
            <span style={{ flex: 1 }} />
            <button className="btn btn-primary" onClick={generate} disabled={busy}>
              {busy ? t('Writing…') : `📝 ${t('Generate Story')}`}
            </button>
          </div>
        </div>

        {aiNote && <p className="badge" style={{ background: 'rgba(255,152,0,0.15)', color: 'var(--vt-orange)' }}>{aiNote}</p>}

        {story && (
          <div>
            <div style={{ display: 'flex', gap: 8, margin: '12px 0', alignItems: 'center' }}>
              <button className="btn btn-sm btn-primary" onClick={speakStory} disabled={speaking}>
                {speaking ? '🔊 …' : '🔊 ' + t('Hear Story')}
              </button>
              <button className="btn btn-sm btn-secondary" onClick={generate}>{t('Regenerate')}</button>
              <span style={{ flex: 1 }} />
              {[w1, w2].filter((v, i, a) => a.indexOf(v) === i).map((w) => {
                const m = wordMeaning(w)
                return (
                  <span key={w} className="badge" style={{ background: 'rgba(46,125,50,0.1)', color: '#2e7d32', padding: '6px 10px' }}>
                    {w} = {lang === 'hi' ? m?.hi : m?.en}
                  </span>
                )
              })}
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {story.map((s, i) => (
                <div key={i} className="card" style={{ padding: '12px 16px', margin: 0 }}>
                  <p style={{ margin: 0, fontSize: 20 }}>{s.sa}</p>
                  <p style={{ margin: '4px 0 0', color: 'var(--vt-muted)', fontSize: 14 }}>{lang === 'hi' ? s.hi : s.en}</p>
                  <p style={{ margin: '2px 0 0', color: 'var(--vt-muted)', fontSize: 13, fontStyle: 'italic' }}>{toIAST(s.sa)}</p>
                </div>
              ))}
            </div>
            <p style={{ marginTop: 14, color: 'var(--vt-muted)', fontSize: 13 }}>
              {t('💡 Tip: tap any word in the app to explore it. Use Voice Mode to practice reading this story aloud!')}
            </p>
          </div>
        )}
      </div>

      {saved.length > 0 && (
        <div className="card" style={{ maxWidth: 760, margin: '20px auto 0', padding: 20 }}>
          <h3 style={{ margin: '0 0 12px' }}>💾 {t('Saved stories')}</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {saved.map((s) => (
              <div key={s.id} className="card" style={{ margin: 0, padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
                <div>
                  <strong>{s.title}</strong>
                  <span style={{ color: 'var(--vt-muted)', fontSize: 13 }}> — {s.word1} · {s.word2}</span>
                  <span className="badge" style={{ marginLeft: 8, background: s.source === 'ai' ? 'rgba(255,152,0,0.15)' : 'rgba(46,125,50,0.1)', color: s.source === 'ai' ? 'var(--vt-orange)' : '#2e7d32' }}>
                    {s.source === 'ai' ? t('AI') : t('Template')}
                  </span>
                  <span style={{ color: 'var(--vt-muted)', fontSize: 12, marginLeft: 8 }}>{new Date(s.createdAt).toLocaleDateString()}</span>
                </div>
                <button className="btn btn-sm btn-secondary" onClick={() => deleteSaved(s.id)}>🗑 {t('Delete')}</button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
